[libraries]
lombok = { module = "org.projectlombok:lombok", version = "1.18.24" }
annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }
fastutil = { module = "it.unimi.dsi:fastutil", version = "8.5.9" }
terminable = { module = "tr.com.infumia:terminable", version = "0.1.3" }
guava = { module = "com.google.guava:guava", version = "31.1-jre" }
netty = { module = "io.netty:netty-all", version = "4.1.77.Final" }
commonslang = { module = "org.apache.commons:commons-lang3", version = "3.12.0" }

[plugins]
spotless = { id = "com.diffplug.spotless", version = "6.11.0" }
nexus = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }
